databases:
  - name: Budget-App
    databaseName: Budget_App_production
    user: niicode
    ipAllowList: []

services:
  - type: web
    name: Budget-App
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget_App_production
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
- type: redis
  name: redis
  ipAllowList: []
  plan: free
  maxmemoryPolicy: noeviction